name: React CI

on:
  push:
    branches:
      - main  # Trigger on push to main branch, adjust if you're using another branch.
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch, adjust if needed.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version you want to use (e.g., 14, 16)

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --ci --reporters=default
